name: NetworkMenuBar
options:
  bundleIdPrefix: com.sakai
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: NetworkMenuBar
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: YES

targets:
  NetworkMenuBar:
    type: application
    platform: macOS
    sources:
      - path: NetworkMenuBar
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: NetworkMenuBar/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: NetworkMenuBar/Resources/NetworkMenuBar.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.sakai.NetworkMenuBar
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
    info:
      path: NetworkMenuBar/Resources/Info.plist
      properties:
        CFBundleName: NetworkMenuBar
        CFBundleDisplayName: NetworkMenuBar
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: NetworkMenuBar/Resources/NetworkMenuBar.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.hardened-runtime: true
        com.apple.security.automation.apple-events: true
